# Goals of this file:
# - Prevent untracked (gitignore'd) files from affecting the build
# - Cache as much as possible to allow quick iteration
#
# Hence the aria2 build should be cached since it rarely changes and takes about 5 times as long to
# build as the updater. To permit caching, the aria2 directory needs to be copied separately before
# the rest of /updater.
#
# git clean -dXff is used to delete all the files specified by .gitignore. This requires the data
# from .git since a checked-in file will not be ignored. For aria2 it is assumed that the data
# is stored in the updater/.git/modules directory.

FROM docker.io/debian:trixie-slim

# Prevents warning spam from Qt 6's rcc
ENV LANG=C.UTF-8

RUN apt-get update && apt-get install -y \
    autoconf \
    autopoint \
    curl \
    gettext \
    g++ \
    g++-mingw-w64-i686-posix \
    git \
    libtool \
    make \
    p7zip-full \
    pkg-config \
    python3 \
    xz-utils

# The Schannel dependencies are spelled with capital letters which causes them not to be found
RUN ln -s libsecur32.a /usr/i686-w64-mingw32/lib/libSecur32.a && \
    ln -s libcrypt32.a /usr/i686-w64-mingw32/lib/libCrypt32.a

############
# Build Qt #
############
WORKDIR /build-qt
COPY md5sums-qt.txt /build-qt/
ENV UPDATER_MODULES=qtbase,qtquickcontrols,qtquickcontrols2,qtsvg,qtgraphicaleffects
RUN curl -LO https://download.qt.io/archive/qt/5.14/5.14.2/single/qt-everywhere-src-5.14.2.tar.xz && \
    md5sum --check --ignore-missing md5sums-qt.txt && \
    tar -xJf qt-everywhere-src-5.14.2.tar.xz && \
    cd qt-everywhere-src-5.14.2 && \
    ./configure -release -static -prefix /qt -qt-zlib -qt-libjpeg -qt-libpng -qt-freetype -qt-pcre -qt-harfbuzz -opengl desktop -opensource -confirm-license -no-qml-debug -no-icu -xplatform win32-g++ -device-option CROSS_COMPILE=i686-w64-mingw32- -optimize-size --c++std=14 -nomake tests -nomake tools -nomake examples -schannel -no-feature-d3d12 && \
    bash -c "make -j`nproc` module-{$UPDATER_MODULES} && make module-{$UPDATER_MODULES}-install_subtargets" && \
    rm -rf /build-qt

###############
# Build aria2 #
###############
COPY aria2 /updater/aria2
COPY .git/modules/aria2 /updater/.git/modules/aria2
COPY build-aria.sh /updater/
WORKDIR /updater/aria2
RUN git clean -dXff
RUN CFLAGS=-Os CXXFLAGS=-Os ../build-aria.sh ARIA2_STATIC=yes --host i686-w64-mingw32

#################
# Build updater #
#################
COPY . /updater
RUN set -e; for D in . quazip fluid; do cd /updater/$D && git clean -dXff; done
WORKDIR /build
RUN /qt/bin/qmake -config release QMAKE_LFLAGS+="-static" INCLUDEPATH+=/qt/include/QtZlib /updater && make -j`nproc`
WORKDIR /release-win
ARG release
RUN if [ -n "$release" ]; then cp /build/release/updater.exe UnvanquishedUpdater.exe && 7z -tzip -mx=9 a UnvUpdaterWin.zip UnvanquishedUpdater.exe; fi
