# Goals of this file:
# - Prevent untracked (gitignore'd) files from affecting the build
# - Cache as much as possible to allow quick iteration
#
# Hence the aria2 build should be cached since it rarely changes and takes about 5 times as long to
# build as the updater. To permit caching, the aria2 directory needs to be copied separately before
# the rest of /updater.
#
# git clean -dXff is used to delete all the files specified by .gitignore. This requires the data
# from .git since a checked-in file will not be ignored. For aria2 it is assumed that the data
# is stored in the updater/.git/modules directory.

FROM docker.io/debian:trixie-slim

# Prevents warning spam from Qt 6's rcc
ENV LANG=C.UTF-8

RUN apt-get update && apt-get install -y \
    autoconf \
    autopoint \
    cmake \
    curl \
    gettext \
    g++ \
    g++-mingw-w64-i686-posix \
    git \
    libtool \
    make \
    ninja-build \
    p7zip-full \
    pkg-config \
    python3 \
    xz-utils

############
# Build Qt #
############
WORKDIR /build-qt

# Build host-mode tools and remove everything apart from the installed bin/ and lib/cmake/
COPY md5sums-qt.txt build-qt.sh qt*.patch cross-toolchain-mingw32.cmake /build-qt/
RUN ./build-qt.sh tools qtbase qtdeclarative qtshadertools && \
    rm -r build_tools && \
    find qt_tools -mindepth 1 -maxdepth 1 ! -name bin ! -name lib ! -name libexec -exec rm -r {} + && \
    find qt_tools/lib -mindepth 1 -maxdepth 1 ! -name cmake -exec rm -r {} +

ARG release
# Note: {foo:+bar} here is a syntax of the Dockerfile, not the shell!
ENV IPO_ARG=${release:+-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON}
RUN BUILDQT_CMAKE_ARGS="${IPO_ARG}"
RUN ./build-qt.sh windows && rm -r build_windows

###############
# Build aria2 #
###############
COPY aria2 /updater/aria2
COPY .git/modules/aria2 /updater/.git/modules/aria2
COPY build-aria.sh /updater/
WORKDIR /updater/aria2
RUN git clean -dXff
RUN CFLAGS=-Os CXXFLAGS=-Os ../build-aria.sh ARIA2_STATIC=yes --host i686-w64-mingw32

#################
# Build updater #
#################
COPY . /updater
RUN set -e; for D in . quazip fluid; do cd /updater/$D && git clean -dXff; done
WORKDIR /build
RUN cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=/build-qt/cross-toolchain-mingw32.cmake -DCMAKE_FIND_ROOT_PATH=/build-qt/qt_windows -DCMAKE_BUILD_TYPE=MinSizeRel ${IPO_ARG} /updater && ninja
RUN mv updater.exe updater-nonstripped.exe && i686-w64-mingw32-strip updater-nonstripped.exe -o updater.exe
WORKDIR /release-win
ARG release
RUN if [ -n "$release" ]; then cp /build/updater.exe UnvanquishedUpdater.exe && 7z -tzip -mx=9 a UnvUpdaterWin.zip UnvanquishedUpdater.exe; fi
